"""empty message

Revision ID: 598d5fa8c979
Revises: 02979a3f9480
Create Date: 2016-03-01 18:41:20.239897

"""

# revision identifiers, used by Alembic.
revision = '598d5fa8c979'
down_revision = '02979a3f9480'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(u'ix_profiles_email', 'profiles', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_profiles_email', table_name='profiles')
    op.drop_table('profiles')
    ### end Alembic commands ###
