"""empty message

Revision ID: 6a29055eb9a0
Revises: None
Create Date: 2016-03-01 17:05:53.796523

"""

# revision identifiers, used by Alembic.
revision = '6a29055eb9a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(u'ix_myprofile_email', 'myprofile', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_myprofile_email', table_name='myprofile')
    op.drop_table('myprofile')
    ### end Alembic commands ###
